CREATE OR REPLACE STORAGE INTEGRATION ZOMATO_S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER= 'S3'
    ENABLED= TRUE
    STORAGE_AWS_ROLE_ARN= '<YOUR_AWS_ROLE_ARN>'
    STORAGE_ALLOWED_LOCATIONS = ('s3://<YOUR_S3_BUCKET>/');


GRANT USAGE ON INTEGRATION ZOMATO_S3_INT TO ROLE DBT_ROLE;

DESC INTEGRATION ZOMATO_S3_INT;