COPY INTO RAW.RESTAURANTS FROM @ZOMATO_RAW_STAGE/restaurants ON_ERROR='CONTINUE';
COPY INTO RAW.FOOD FROM @ZOMATO_RAW_STAGE/food ON_ERROR='CONTINUE';
COPY INTO RAW.MENU FROM @ZOMATO_RAW_STAGE/menu ON_ERROR='CONTINUE';
COPY INTO RAW.ORDER_ITEMS FROM @ZOMATO_RAW_STAGE/order_items ON_ERROR='CONTINUE';
COPY INTO RAW.ORDERS FROM @ZOMATO_RAW_STAGE/orders ON_ERROR='CONTINUE';
COPY INTO RAW.REVIEWS FROM @ZOMATO_RAW_STAGE/reviews ON_ERROR='CONTINUE';
COPY INTO RAW.USERS FROM @ZOMATO_RAW_STAGE/users ON_ERROR='CONTINUE';
